#!/bin/bash

# zed is now run by launctl, so this script should not be required.
exit 0

ZED=/usr/local/zfs/bin/zed

set +e
pgrep zed 1>/dev/null
pgrepret=$?
set -e

if [ $pgrepret -ne 0 ] ; then
	echo "zed not started"
	if [ -f $ZED ] ; then
		echo "Starting zed ..."
			$ZED
	else
		echo "zed binary $ZED not found"
	fi
else
	echo "zed already running"
fi

exit 0
