#!/bin/bash

set +e
pgrep zed 1>/dev/null
pgrepret=$?
set -e

if [ $pgrepret -ne 0 ] ; then
	echo "zed not started"
	if [ -f /usr/sbin/zed ] ; then
		echo "Starting zed ..."
			/usr/sbin/zed
	else
		echo "zed binary /usr/sbin/zed not found"
	fi
else
	echo "zed already running"
fi

exit 0
