# SPDX-License-Identifier: CDDL-1.0
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# https://opensource.org/license/CDDL-1.0.

dist_noinst_DATA += \
	%D%/README.md \
	%D%/memory-pressure.c \
	%D%/prepare-user-data \
	%D%/prepare-zvol-swap-guest.sh \
	%D%/repro-zvol-swap-stall.sh \
	%D%/run.py \
	%D%/zvol-swap-boot.sh \
	%D%/zvol-swap.service

SHELLCHECKSCRIPTS += \
	%D%/prepare-zvol-swap-guest.sh \
	%D%/repro-zvol-swap-stall.sh \
	%D%/zvol-swap-boot.sh
