env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  matrix:
    freebsd_instance:
      image_family: freebsd-13-5
    freebsd_instance:
      image_family: freebsd-14-2
    freebsd_instance:
      image_family: freebsd-15-0-snap
  prepare_script:
    - pkg install -y autoconf automake libtool gettext-runtime gmake ksh93 py311-packaging py311-cffi py311-sysctl
  configure_script:
    - env MAKE=gmake ./autogen.sh
    - env MAKE=gmake ./configure --with-config="user" --with-python=3.11
  build_script:
    - gmake -j `sysctl -n kern.smp.cpus`
  install_script:
    - gmake install
