#!/bin/sh
#
# Copyright (C) 2016 Canonical
#   
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
echo -n "kernel smoke test, create and destroy ZFS filesystems: "
TMP=/tmp
VDEV0=${TMP}/pool0-$$.img
VDEV1=${TMP}/pool1-$$.img
POOL=pool-smoke-$$
ZFSFS="test tmp example data1 data2 data3"

dd if=/dev/zero of=${VDEV0} bs=1M count=512 > /dev/null 2>&1
dd if=/dev/zero of=${VDEV1} bs=1M count=512 > /dev/null 2>&1

zpool create ${POOL} ${VDEV0} ${VDEV1}
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zpool create failed, exit code=$ret"
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

#
# And populate with ZFS file systems
#
for fs in ${ZFSFS}
do
	zfs create ${POOL}/$fs 
	ret=$?
	if [ $ret -ne 0 ]; then
		echo "FAILED: zfs create filesystem $fs failed, exit code=$ret"
		zpool destroy ${POOL}
		rm ${VDEV0} ${VDEV1}
		exit 1
	fi
	
	zfs set quota=128M ${POOL}/$fs
	ret=$?
	if [ $ret -ne 0 ]; then
		echo "FAILED: zfs set quota on $fs failed, exit code=$ret"
		zpool destroy ${POOL}
		rm ${VDEV0} ${VDEV1}
		exit 1
	fi

	zfs set compression=on ${POOL}/$fs
	ret=$?
	if [ $ret -ne 0 ]; then
		echo "FAILED: zfs set compression on $fs failed, exit code=$ret"
		zpool destroy ${POOL}
		rm ${VDEV0} ${VDEV1}
		exit 1
	fi
done

#
# And destroy ZFS file systems
#
for fs in ${ZFSFS}
do
	zfs destroy ${POOL}/$fs 
	ret=$?
	if [ $ret -ne 0 ]; then
		echo "FAILED: zfs destroy filesystem $fs failed, exit code=$ret"
		zpool destroy ${POOL}
		rm ${VDEV0} ${VDEV1}
		exit 1
	fi
done

zpool destroy ${POOL}
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zpool destroy failed, exit code=$ret"
	#
	# destroy failed, try to clean up, but this
	# wil probably fail
	#
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

rm ${VDEV0} ${VDEV1}
echo "PASSED"
exit 0
