#!/bin/sh
#
# Copyright (C) 2016 Canonical
#   
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
echo -n "kernel smoke test, ZFS snapshot: "
TMP=/tmp
VDEV0=${TMP}/pool0-$$.img
VDEV1=${TMP}/pool1-$$.img
POOL=pool-smoke-$$
MARKER=/${POOL}/test/marker

dd if=/dev/zero of=${VDEV0} bs=1M count=512 > /dev/null 2>&1
dd if=/dev/zero of=${VDEV1} bs=1M count=512 > /dev/null 2>&1

zpool create ${POOL} ${VDEV0} ${VDEV1}
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zpool create failed, exit code=$ret"
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

zfs create ${POOL}/test
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zfs create failed, exit code=$ret"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

#
# Populate with files..
#
cp -rp /etc /${POOL}/test
echo $$ > ${MARKER}

#
# Make a snapshot
#
zfs snapshot -r ${POOL}/test@snap
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zfs snapshot failed, exit code=$ret"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

#
# Remove files
#
rm -rf /${POOL}/test/etc ${MARKER}

#
# Roll back
#
zfs rollback ${POOL}/test@snap
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zfs rollback failed, exit code=$ret"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

#
# Check rolled back marker contains sane data
#
if [ ! -e ${MARKER} ]; then
	echo "FAILED: zfs rollback failed, ${MARKER} not restored"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi
data=$(cat ${MARKER})
if [ $data -ne $$ ]; then
	echo "FAILED: zfs rollback failed, ${MARKER} contained unexpected data"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

zfs destroy ${POOL}/test@snap
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zfs destroy snapshot failed, exit code=$ret"
	zpool destroy ${POOL}
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

zpool destroy ${POOL}
ret=$?
if [ $ret -ne 0 ]; then
	echo "FAILED: zpool destroy failed, exit code=$ret"
	#
	# destroy failed, try to clean up, but this
	# wil probably fail
	#
	rm ${VDEV0} ${VDEV1}
	exit 1
fi

rm ${VDEV0} ${VDEV1}
echo "PASSED"
exit 0
