extern crate cbindgen;

use cbindgen::Config;
use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let warning = "/*
 * Warning: Don't modify this file manually. It was autogenerated by cbindgen.
 */";

    let config = Config {
        language: cbindgen::Language::C,
        tab_width: 8,
        line_length: 80,
        cpp_compat: true,
        autogen_warning: Some(String::from(warning)),
        ..Default::default()
    };

    cbindgen::generate_with_config(&crate_dir, config)
        .unwrap()
        .write_to_file("../../../include/libzoa.h");
}
