# SPDX-License-Identifier: CDDL-1.0
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# This run file contains all tests related to the iolimit functionality.
#
# Approximate run time: 1 hour 10 minutes
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 7200
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
outputdir = /var/tmp/test_results
tags = ['iolimit']

[tests/functional/iolimit]
tests = ['filesystem_bw_combined',
    'filesystem_bw_hierarchical_horizontal',
    'filesystem_bw_hierarchical_vertical_read',
    'filesystem_bw_hierarchical_vertical_total',
    'filesystem_bw_hierarchical_vertical_write',
    'filesystem_bw_multiple',
    'filesystem_bw_recv',
    'filesystem_bw_send',
    'filesystem_bw_single',
    'filesystem_op_single',
    'filesystem_op_multiple',
    'inheritance',
    'volume_bw_combined',
    'volume_bw_hierarchical_horizontal',
    'volume_bw_hierarchical_vertical_read',
    'volume_bw_hierarchical_vertical_total',
    'volume_bw_hierarchical_vertical_write',
    'volume_bw_multiple',
    'volume_bw_recv',
    'volume_bw_send',
    'volume_bw_single']
tags = ['iolimit']
