.\" SPDX-License-Identifier: CDDL-1.0
.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" https://opensource.org/license/CDDL-1.0.
.\"
.\" Copyright 2013 Darik Horn <dajhorn@vanadac.com>. All rights reserved.
.\"
.Dd May 26, 2021
.Dt FSCK.ZFS 8
.Os
.
.Sh NAME
.Nm fsck.zfs
.Nd dummy ZFS filesystem checker
.Sh SYNOPSIS
.Nm
.Op Ar options
.Ar dataset Ns No …
.
.Sh DESCRIPTION
.Nm
is a thin shell wrapper that at most checks the status of a dataset's container
pool.
It is installed by OpenZFS because some Linux
distributions expect a fsck helper for all filesystems.
.Pp
If more than one
.Ar dataset
is specified, each is checked in turn and the results binary-ored.
.
.Sh OPTIONS
Ignored.
.
.Sh NOTES
ZFS datasets are checked by running
.Nm zpool Cm scrub
on the containing pool.
An individual ZFS dataset is never checked independently of its pool,
which is unlike a regular filesystem.
.Pp
However, the
.Xr fsck 8
interface still allows it to communicate some errors: if the
.Ar dataset
is in a degraded pool, then
.Nm
will return exit code
.Sy 4
to indicate an uncorrected filesystem error.
.Pp
Similarly, if the
.Ar dataset
is in a faulted pool and has a legacy
.Pa /etc/fstab
record, then
.Nm
will return exit code
.Sy 8
to indicate a fatal operational error.
.Sh SEE ALSO
.Xr fstab 5 ,
.Xr fsck 8 ,
.Xr zpool-scrub 8
