.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or https://opensource.org/licenses/CDDL-1.0.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2013 Darik Horn <dajhorn@vanadac.com>. All rights reserved.
.\"
.Dd May 24, 2021
.Dt MOUNT.ZFS 8
.Os
.
.Sh NAME
.Nm mount.zfs
.Nd mount ZFS filesystem
.Sh SYNOPSIS
.Nm
.Op Fl sfnvh
.Op Fl o Ar options
.Ar dataset
.Ar mountpoint
.
.Sh DESCRIPTION
The
.Nm
helper is used by
.Xr mount 8
to mount filesystem snapshots and
.Sy mountpoint= Ns Ar legacy
ZFS filesystems, as well as by
.Xr zfs 8
when the
.Sy ZFS_MOUNT_HELPER
environment variable is not set.
Users should should invoke either
.Xr mount 8
or
.Xr zfs 8
in most cases.
.Pp
.Ar options
are handled according to the
.Em Temporary Mount Point Properties
section in
.Xr zfsprops 7 ,
except for those described below.
.Pp
If
.Pa /etc/mtab
is a regular file and
.Fl n
was not specified, it will be updated via libmount.
.
.Sh OPTIONS
.Bl -tag -width "-o xa"
.It Fl s
Ignore unknown (sloppy) mount options.
.It Fl f
Do everything except actually executing the system call.
.It Fl n
Never update
.Pa /etc/mtab .
.It Fl v
Print resolved mount options and parser state.
.It Fl h
Print the usage message.
.It Fl o Ar zfsutil
This private flag indicates that
.Xr mount 8
is being called by the
.Xr zfs 8
command.
.El
.
.Sh SEE ALSO
.Xr fstab 5 ,
.Xr mount 8 ,
.Xr zfs-mount 8
