.\" SPDX-License-Identifier: CDDL-1.0
.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" https://opensource.org/license/CDDL-1.0.
.\"
.\" Copyright (c) 2020 by Delphix. All rights reserved.
.\"
.Dd July 11, 2022
.Dt ZFS_IDS_TO_PATH 8
.Os
.
.Sh NAME
.Nm zfs_ids_to_path
.Nd convert objset and object ids to names and paths
.Sh SYNOPSIS
.Nm
.Op Fl v
.Ar pool
.Ar objset-id
.Ar object-id
.
.Sh DESCRIPTION
The
.Sy zfs_ids_to_path
utility converts a provided objset and object ids
into a path to the file they refer to.
.Bl -tag -width "-D"
.It Fl v
Verbose.
Print the dataset name and the file path within the dataset separately.
This will work correctly even if the dataset is not mounted.
.El
.
.Sh SEE ALSO
.Xr zdb 8 ,
.Xr zfs 8
