.\" SPDX-License-Identifier: CDDL-1.0
.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" https://opensource.org/license/CDDL-1.0.
.\"
.\" Copyright (c) 2007, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright (c) 2012, 2018 by Delphix. All rights reserved.
.\" Copyright (c) 2012 Cyril Plisko. All Rights Reserved.
.\" Copyright (c) 2017 Datto Inc.
.\" Copyright (c) 2018 George Melikov. All Rights Reserved.
.\" Copyright 2017 Nexenta Systems, Inc.
.\" Copyright (c) 2017 Open-E, Inc. All Rights Reserved.
.\"
.Dd July 11, 2022
.Dt ZPOOL-RESILVER 8
.Os
.
.Sh NAME
.Nm zpool-resilver
.Nd resilver devices in ZFS storage pools
.Sh SYNOPSIS
.Nm zpool
.Cm resilver
.Ar pool Ns …
.
.Sh DESCRIPTION
Starts a resilver of the specified pools.
If an existing resilver is already running it will be restarted from the
beginning.
Any drives that were scheduled for a deferred
resilver will be added to the new one.
This requires the
.Sy resilver_defer
pool feature.
.Pp
Due to concurrent writes on a live system, it is possible for
resilver to progress beyond 100% completion.
.
.Sh SEE ALSO
.Xr zpool-iostat 8 ,
.Xr zpool-online 8 ,
.Xr zpool-reopen 8 ,
.Xr zpool-replace 8 ,
.Xr zpool-scrub 8 ,
.Xr zpool-status 8
