.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright (c) 2007, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright (c) 2012, 2018 by Delphix. All rights reserved.
.\" Copyright (c) 2012 Cyril Plisko. All Rights Reserved.
.\" Copyright (c) 2017 Datto Inc.
.\" Copyright (c) 2018 George Melikov. All Rights Reserved.
.\" Copyright 2017 Nexenta Systems, Inc.
.\" Copyright (c) 2017 Open-E, Inc. All Rights Reserved.
.\"
.Dd May 31, 2021
.Dt ZPOOL-LABELCLEAR 8
.Os
.
.Sh NAME
.Nm zpool-labelclear
.Nd remove ZFS label information from device
.Sh SYNOPSIS
.Nm zpool
.Cm labelclear
.Op Fl f
.Ar device
.
.Sh DESCRIPTION
Removes ZFS label information from the specified
.Ar device .
If the
.Ar device
is a cache device, it also removes the L2ARC header
(persistent L2ARC).
The
.Ar device
must not be part of an active pool configuration.
.Bl -tag -width Ds
.It Fl f
Treat exported or foreign devices as inactive.
.El
.
.Sh SEE ALSO
.Xr zpool-destroy 8 ,
.Xr zpool-detach 8 ,
.Xr zpool-remove 8 ,
.Xr zpool-replace 8
