// SPDX-License-Identifier: CDDL-1.0
/*
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source.  A copy of the CDDL is also available via the Internet at
 * https://opensource.org/license/CDDL-1.0.
 */

#ifndef _SPL_SIGNAL_H
#define	_SPL_SIGNAL_H

// #include <sys/sched.h>
// #include <sys/vm.h>
// #include <sys/proc.h>
// #include <sys/thread.h>
#include_next <signal.h>

#define	FORREAL		0	/* Usual side-effects */
#define	JUSTLOOKING	1	/* Don't stop the process */

#define	SIGEV_NONE	0	/* No async notification. */
#define	SIGEV_SIGNAL	1	/* Generate a queued signal. */
#define	SIGEV_THREAD	2	/* Call back from another pthread. */

#define	SIGHUP		1
#define	SIGALRM		14
#define	SIGPIPE		13
#define	SIGCHLD		18
#define	SIGSTOP		23
#define	SIGRTMIN	24
#define	SIGUSR1		30	/* user defined signal 1 */
#define	SIGUSR2		31	/* user defined signal 2 */

#define	SI_TIMER 0x10003 /* Signal generated by expiration of */

struct proc;

// extern int
// thread_issignal(struct proc *, thread_t, sigset_t);
#define	SA_RESTART	0x00000004
#define	SA_SIGINFO	0x00000008

#define	SIG_SETMASK	3

typedef struct __siginfo {
	/* Windows version goes here */
	void *si_addr;
	int si_code;
} siginfo_t;

typedef struct {
	unsigned long sig[1];
} sigset_t;

typedef void (*sighandler_t) (int);

struct sigaction {
	union
	{
	/* Used if SA_SIGINFO is not set.  */
		sighandler_t sa_handler;
	/* Used if SA_SIGINFO is set.  */
		void (*sa_sigaction) (int, siginfo_t *, void *);
	};
	sigset_t sa_mask;
	/* Special flags.  */
	int sa_flags;
};

union sigval {
	int	sival_int;
	void	*sival_ptr;
};

struct sigevent {
	int	sigev_notify;		/* Notification type */
	int	sigev_signo;		/* Signal number */
	union sigval sigev_value;	/* Signal value */
	void	(*sigev_notify_function)(union sigval);
	void	*sigev_notify_attributes;
};

/*
 * The "why" argument indicates the allowable side-effects of the call:
 *
 * FORREAL:  Extract the next pending signal from p_sig into p_cursig;
 * stop the process if a stop has been requested or if a traced signal
 * is pending.
 *
 * JUSTLOOKING:  Don't stop the process, just indicate whether or not
 * a signal might be pending (FORREAL is needed to tell for sure).
 */
#define	threadmask \
	(sigmask(SIGILL)|sigmask(SIGTRAP)|				 \
	    sigmask(SIGIOT)|sigmask(SIGEMT)|			 \
	    sigmask(SIGFPE)|sigmask(SIGBUS)|			 \
	    sigmask(SIGSEGV)|sigmask(SIGSYS)|			 \
	    sigmask(SIGPIPE)|sigmask(SIGKILL)|			 \
	    sigmask(SIGTERM)|sigmask(SIGINT))

static inline int
issig(int why)
{
	return (0);
}

#define	signal_pending(p) issig(0)

extern int sigemptyset(sigset_t *set);
extern int sigfillset(sigset_t *set);
extern int sigaddset(sigset_t *set, int sig);
extern int sigdelset(sigset_t *set, int sig);
extern int sigismember(sigset_t *set, int sig);
extern int sigaction(int sig, struct sigaction *sa, struct sigaction *osa);
extern int sigprocmask(int operation, sigset_t *set, sigset_t *oset);
extern int pause(void);
extern int kill(int pid, int sig);
extern int sigwait(const sigset_t *set, int *sig);
extern int sigsuspend(const sigset_t *mask);
extern int sigpending(sigset_t *set);

#endif /* SPL_SIGNAL_H */
