dnl #
dnl # Default ZFS user configuration
dnl #
AC_DEFUN([ZFS_AC_CONFIG_USER], [
	ZFS_AC_CONFIG_USER_ARCH
	ZFS_AC_CONFIG_USER_LIBEFI
	ZFS_AC_CONFIG_USER_LIBDISKMGT
	ZFS_AC_CONFIG_USER_LIBSHARE
	ZFS_AC_CONFIG_USER_IOCTL
	ZFS_AC_CONFIG_USER_ZLIB
])
