; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define Root SourcePath+"..\..\..\"

#define MyAppName "OpenZFS On Windows"
#define MyAppPublisher "OpenZFS"
#define MyAppURL "http://www.openzfsonwindows.org/"

; Attempt to read in the gitrev version from the header file.
#define VerFile FileOpen(Root + "include\zfs_gitrev.h")
#define VerStr FileRead(VerFile)       ; "// This file is only used on Windows and CMake, other platforms"
#define VerStr FileRead(VerFile)       ; "// see scripts/make-gitrev.sh"
#define VerStr FileRead(VerFile)       ; "#define	ZFS_META_GITREV "zfs-2.0.0-7-g689dbcfbf-dirty""
; #pragma message VerStr + " readline"
#expr FileClose(VerFile)
#undef VerFile
; Parse out 2.0.0-7-g689dbcfbf-dirty and delete the double-quote
#define MyAppVersion StringChange(Copy(VerStr, 33), '"','')

#pragma message MyAppVersion + " is version"

#if MyAppVersion == ""
#error Failed to read version from include/zfs_gitrev.h
#endif

#include "environment.iss"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{61A38ED1-4D3F-4869-A8D5-87A58A301D56}
AppName={#MyAppName}-debug
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}-{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf64}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile={#SourcePath}\OPENSOLARIS.LICENSE.txt
InfoBeforeFile={#SourcePath}\readme.txt
OutputBaseFilename=OpenZFSOnWindows-debug-{#MyAppVersion}
SetupIconFile={#SourcePath}\openzfs.ico
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
OutputDir={#SourcePath}\..
ChangesEnvironment=true
WizardSmallImageFile="{#SourcePath}\openzfs-small.bmp"
WizardImageFile="{#SourcePath}\openzfs-large.bmp"
; Tools/Configure Sign Tools -> Add ->
; "signtoola" = C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe sign /sha1 09A7835D2496C08389CF1CC1031EF73BAE897A08 /n $qWest Coast Enterprises Limited$q /t http://ts.digicert.com /as /fd sha256 /td sha256 /d $qOpenZFS on Windows$q $f
; "signtoolb" = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe sign /sha1 ab8e4f6b94cecfa4638847122b511e507e147c50 /as /n $qJoergen Lundman$q /tr http://timestamp.digicert.com /td sha256 /fd sha256 /d $qOpenZFS on Windows$q $f"
; "signtoolc" = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe sign /v /fd sha256 /n $qOpenZFS Test Signing Certificate$q /t http://timestamp.digicert.com $f"
; SignTool=signtoola
; SignTool=signtoolb
SignTool=signtoolc
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]
function ExecHiddenWait(const FileName, Params, WorkingDir: string; var ExitCode: Integer): Boolean;
begin
  // SW_HIDE or SW_SHOW
  Result := Exec(FileName, Params, WorkingDir, SW_SHOW, ewWaitUntilTerminated, ExitCode);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var ExePath: string; Code: Integer; Ok: Boolean;
begin
    if (CurStep = ssPostInstall) then
    begin
      if (WizardIsTaskSelected('envPath')) then
      begin
        EnvAddPath(ExpandConstant('{app}'));
      end;
    
      ExePath := ExpandConstant('{app}\zfsinstaller.exe');
      if FileExists(ExePath) then
      begin
        Ok := ExecHiddenWait(ExePath, 'postflight', '', Code);
      end;
    end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
    if CurUninstallStep = usPostUninstall
    then EnvRemovePath(ExpandConstant('{app}'));
end;

function RunPreflightAndFailIfNeeded(): Boolean;
var
  ExePath: string;
  ResultCode: Integer;
  Ok: Boolean;
begin
  // Make the bundled exe available in {tmp}
  ExtractTemporaryFile('zfsinstaller.exe');
  ExePath := ExpandConstant('{tmp}\zfsinstaller.exe');

  // Optional: add args like "preflight --attempt-export --quiet"
  // SW_HIDE or SW_SHOW
  Ok := Exec(ExePath, 'preflight', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
  if not Ok then
  begin
    SuppressibleMsgBox(
      'Failed to run preflight (zfsinstaller.exe). Installation cannot continue.',
      mbCriticalError, MB_OK, MB_OK);
    Result := False;
    Exit;
  end;

  // Your preflight contract:
  //  0  = OK to proceed (no pools, or successfully exported)
  // !=0 = Pools are imported and could not be auto-exported (user action needed)
  if ResultCode <> 0 then
  begin
    // Keep this message crisp; users will see it right before install begins
    SuppressibleMsgBox(
      'OpenZFS preflight check detected imported pools.'#13#10+
      'Please export all pools (e.g. "zpool export -a") and run the installer again.',
      mbCriticalError, MB_OK, MB_OK);
    Result := False;
    Exit;
  end;

  Result := True;
end;

// Called right before files are installed. Return a non-empty string to abort.
function PrepareToInstall(var NeedsRestart: Boolean): string;
begin
  if not RunPreflightAndFailIfNeeded() then
    Result := 'Preflight checks failed. Pools are still imported.'
  else
    Result := '';
end;

function InitializeUninstall(): Boolean;
var ExePath: string; Code: Integer; Ok: Boolean;
begin
  Result := True;  // default allow
  ExePath := ExpandConstant('{app}\zfsinstaller.exe');

  if FileExists(ExePath) then
  begin
    Ok := ExecHiddenWait(ExePath, 'preflight', '', Code);
    if not Ok then
    begin
      SuppressibleMsgBox('Failed to run pre-uninstall preflight (zfsinstaller.exe).', mbCriticalError, MB_OK, MB_OK);
      Result := False; Exit;
    end;

    if Code <> 0 then
    begin
      SuppressibleMsgBox(
        'Uninstall preflight detected imported pools or couldn’t safely export them.'#13#10+
        'Please export all pools (e.g. "zpool export -a") and retry uninstall.',
        mbCriticalError, MB_OK, MB_OK);
      Result := False; Exit;
    end;
  end;
end;


[Tasks]
Name: envPath; Description: "Add OpenZFS to PATH variable"

[Files]
Source: "{#Root}\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\CODE_OF_CONDUCT.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\kstat\kstat.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zfsinstaller\zfsinstaller.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zed_service\zed_service.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zfs_tray\zfs_tray.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zpool\zpool.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zfs\zfs.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zdb\zdb.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zed\zed.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zstream\zstreamdump.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\raidz_test\raidz_test.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\driver\OpenZFS.sys"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\driver\OpenZFS.cat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\driver\OpenZFS.inf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\driver\OpenZFS.man"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#Root}\x64\Debug\ZFSin.cer"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#Root}\zfs\cmd\arcstat\arcstat.pl"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\driver\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zstream\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zpool\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zfs\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zdb\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\zed\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\raidz_test\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zfsinstaller\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\kstat\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#SourcePath}\HowToDebug.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\contrib\windows\parsedump\*.*"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\contrib\windows\EnableOpenZFSLocalCrashDumps.reg"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\contrib\windows\DisableOpenZFSLocalCrashDumps.reg"; DestDir: "{app}\symbols"; Flags: ignoreversion
Source: "{#Root}\scripts\zfs_prepare_disk"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\cmd\zpool\compatibility.d\*"; DestDir: "{app}\compatibility.d"; Flags: ignoreversion
Source: "{#Root}\cmd\zpool\zpool.d\*"; DestDir: "{app}\zpool.d"; Flags: ignoreversion
Source: "{#Root}\cmd\zed\os\windows\zed.d\*"; DestDir: "{app}\zed.d"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\zvol\driver\OpenZVOL.sys"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\zvol\driver\OpenZVOL.cat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\zvol\driver\OpenZVOL.inf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\module\os\windows\zvol\driver\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion
; VSS provider (enables Previous Versions for ZFS snapshots)
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zfs_vss_provider\zfs_vss_provider.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Root}\out\build\x64-Debug\cmd\os\windows\zfs_vss_provider\*.pdb"; DestDir: "{app}\symbols"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
[UninstallDelete]
Type: files; Name: "{app}\zed.pid"
Type: files; Name: "{app}\zed.state"
Type: files; Name: "{app}\cbuf.txt"

[Icons]
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commonstartup}\OpenZFS Tray"; Filename: "{app}\zfs_tray.exe"


[Run]
Filename: "{app}\ZFSInstaller.exe"; Parameters: "install -z .\OpenZFS.inf .\OpenZVOL.inf"; StatusMsg: "Installing Driver..."; Flags: runascurrentuser;
; Register the ZFS VSS Provider so Previous Versions works for ZFS snapshots
Filename: "{app}\zfs_vss_provider.exe"; Parameters: "/install"; StatusMsg: "Registering VSS Provider..."; Flags: runhidden waituntilterminated
; Restart the VSS service so it picks up the newly registered provider
Filename: "net.exe"; Parameters: "stop vss"; Flags: runhidden waituntilterminated
Filename: "net.exe"; Parameters: "start vss"; Flags: runhidden waituntilterminated
; zfs_tray bit next
Filename: "sc.exe"; Parameters: "create OpenZFS_Tray binPath= ""{app}\zed_service.exe"" start= auto DisplayName= ""OpenZFS Tray"""; Flags: runhidden waituntilterminated
Filename: "sc.exe"; Parameters: "start OpenZFS_Tray"; Flags: runhidden
Filename: "{app}\zfs_tray.exe"; Flags: postinstall nowait runasoriginaluser


[UninstallRun]
; First zfs_tray
Filename: "taskkill.exe"; Parameters: "/IM zfs_tray.exe /T /F"; RunOnceId: "stoptray"; Flags: runhidden
Filename: "sc.exe"; Parameters: "stop OpenZFS_Tray"; RunOnceId: "stoptrayservice"; Flags: runhidden waituntilterminated
Filename: "sc.exe"; Parameters: "delete OpenZFS_Tray"; RunOnceId: "deletetrayservice"; Flags: runhidden waituntilterminated
; VSS provider - unregister before files are removed
Filename: "{app}\zfs_vss_provider.exe"; Parameters: "/uninstall"; RunOnceId: "vssinst"; Flags: runhidden waituntilterminated
; Kernel
Filename: "{app}\ZFSInstaller.exe"; Parameters: "uninstall -z .\OpenZFS.inf .\OpenZVOL.inf"; RunOnceId: "driver"; Flags: runascurrentuser;

[Registry]
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{app}"
