#
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2013 by Delphix. All rights reserved.
#

.PARALLEL: $(SUBDIRS)

SUBDIRS = acl \
	atime \
	bootfs \
	cache \
	cachefile \
	clean_mirror \
	cli_root \
	cli_user \
	compression \
	ctime \
	delegate \
	devices \
	exec \
	features \
	grow_pool \
	grow_replicas \
	history \
	inheritance \
	interop \
	inuse \
	large_files \
	largest_pool \
	link_count \
	mdb \
	migration \
	mmap \
	mount \
	mv_files \
	nestedfs \
	no_space \
	nopwrite \
	online_offline \
	pool_names \
	poolversion \
	privilege \
	quota \
	redundancy \
	refquota \
	refreserv \
	rename_dirs \
	replacement \
	reservation \
	rootpool \
	rsend \
	scrub_mirror \
	slog \
	snapshot \
	snapused \
	sparse \
	threadsappend \
	truncate \
	userquota \
	utils_test \
	write_dirs \
	xattr \
	zvol


include $(SRC)/test/Makefile.com
