#!/bin/bash

inst_rules "$moddir/90-zfs.rules"
inst_rules /etc/udev/rules.d/60-zpool.rules
inst_rules /etc/udev/rules.d/60-zvol.rules
inst /etc/zfs/zdev.conf
inst /etc/hostid
dracut_install zfs
dracut_install zpool
dracut_install zpool_layout
dracut_install zpool_id
dracut_install zvol_id
dracut_install mount.zfs
dracut_install hostid
inst_hook cmdline 95 "$moddir/parse-zfs.sh"
inst_hook mount 98 "$moddir/mount-zfs.sh"
inst_hook pre-udev 29 "$moddir/zfs-genrules.sh"
