$(MODULE)-objs += $(TARGET_ASM_DIR)/sha256-ssse3-asm.o
$(MODULE)-objs += $(TARGET_ASM_DIR)/sha256-avx-asm.o
$(MODULE)-objs += $(TARGET_ASM_DIR)/sha256-avx2-asm.o
$(MODULE)-objs += $(TARGET_ASM_DIR)/sha256_x86.o
